Function 7 (My rank 10th):
Percentile = 74.29th percentile I used the open-source Python library Hyperopt with the Tree Parzen Estimator to optimize the hyperparameters of a gradient boosting machine. Function 7: "Sometimes Lazy is Best" and its optimization. This function involves optimizing six hyperparameters of a machine learning model, with the objective of minimizing the output. The problem hints that the model is popular and frequently used, suggesting that I might find existing optimizations for it.

Strategy
1.	Analyze Initial Data:
Find the input combination that produced the minimum output.
o	Look for any patterns in the initial data.
2.	Research the Model:
Given the hint, try to identify the machine learning model.
Search for existing research or best practices for optimizing its hyperparameters.
3.	Refine the Search:
Use the information from the research and the initial data analysis to guide further queries.
Consider using an optimization algorithm if the search space is complex.

* **Choosing an Optimization Algorithm:** Bayesian Optimization is generally a strong choice for this type of problem, especially when model evaluation is computationally expensive. Specifically, I find Hyperopt, which uses the Tree-structured Parzen Estimator (TPE) algorithm, to be a good balance of effectiveness and ease of use in a Google Colab environment.

When using Hyperopt, my objective function was designed to maximize an acquisition function, such as Expected Improvement (EI), rather than directly optimizing the model's performance metric. Hyperopt is designed to minimize, so I would return the negative of the acquisition function's value (e.g., negative EI). This means that finding the minimum loss for Hyperopt corresponds to finding the maximum expected improvement. The parameters found by Hyperopt's `fmin` function are the next recommended hyperparameter values to test in my actual model or function.










In [ ]:
import numpy as np

initial_inputs = np.load('/content/initial_inputs.npy')
initial_outputs = np.load('/content/initial_outputs.npy')

print("Initial Inputs Shape:", initial_inputs.shape)
print("Initial Outputs Shape:", initial_outputs.shape)
print("Initial Inputs:\n", initial_inputs)
print("Initial Outputs:\n", initial_outputs)

Initial Inputs Shape: (30, 6)
Initial Outputs Shape: (30,)
Initial Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.4

In [ ]:
import numpy as np

# Load the initial inputs and outputs from the .npy files
initial_inputs = np.load('/content/initial_inputs.npy')
initial_outputs = np.load('/content/initial_outputs.npy')

# Find the input that resulted in the minimum output
best_index = np.argmin(initial_outputs)
best_input = initial_inputs[best_index]

print("Input with minimum output:")
print(best_input)
print("Output value:", initial_outputs[best_index])

Input with minimum output:
[0.87987128 0.39796199 0.00363456 0.95699064 0.26451373 0.11486924]
Output value: 0.0027014650245082332


In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, space_eval

initial_inputs = np.array([
    # ... your initial_inputs data here ...
    [0.47682313, 0.34094195, 0.01433523, 0.88013956, 0.9986547, 0.07966402]
])

initial_outputs = np.array([
    # ... your initial_outputs data here ...
    0.09541116
])

def objective(index):
    return abs(initial_outputs[index])  # Minimize absolute value (closest to zero)

space = hp.randint('index', 0, len(initial_outputs))

best = fmin(objective, space, algo=tpe.suggest, max_evals=1)

best_index = best['index']
first_query = initial_inputs[best_index]

print("Best Index:", best_index)
print("First Query:", first_query)

100%|██████████| 1/1 [00:00<00:00, 252.32trial/s, best loss: 0.09541116]
Best Index: 0
First Query: [0.47682313 0.34094195 0.01433523 0.88013956 0.9986547  0.07966402]


In [ ]:
initial_inputs = np.load('/content/initial_inputs.npy')
initial_outputs = np.load('/content/initial_outputs.npy')

In [ ]:
min_output_index = np.argmin(initial_outputs)

In [ ]:
corresponding_input = initial_inputs[min_output_index]

In [ ]:
print("Index of minimum output:", min_output_index)
print("Corresponding input values:", corresponding_input)

Index of minimum output: 19
Corresponding input values: [0.87987128 0.39796199 0.00363456 0.95699064 0.26451373 0.11486924]


In [ ]:
!pip install hyperopt==0.2.7

In [ ]:
def objective(params):
  """Objective function to minimize."""
  # Assuming your evaluation function is named 'evaluate_model'
  # and takes a list of input values as arguments
  output = evaluate_model(list(params.values()))
  return {'loss': output, 'status': STATUS_OK}

In [ ]:
from hyperopt import hp, fmin, tpe, STATUS_OK, Trials

# Define your lower and upper bounds for each parameter
lower_bound1 = 0.0  # Example: lower bound for param1 is 0.0
upper_bound1 = 1.0  # Example: upper bound for param1 is 1.0
lower_bound2 = -1.0 # Example: lower bound for param2 is -1.0
upper_bound2 = 1.0  # Example: upper bound for param2 is 1.0
# ... define other lower and upper bounds ...
lower_bound6 = 0.2  # Example: lower bound for param6 is 0.2
upper_bound6 = 0.8  # Example: upper bound for param6 is 0.8

space = {
    'param1': hp.uniform('param1', lower_bound1, upper_bound1),
    'param2': hp.uniform('param2', lower_bound2, upper_bound2),
    # ... define other parameters and their ranges ...
    'param6': hp.uniform('param6', lower_bound6, upper_bound6),
}

In [ ]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

In [ ]:
import numpy as np

# Generate a random query for the 6D input space
next_query = np.random.uniform(0, 1, size=6)

print("Next query (random):", next_query)

Next query (random): [0.51370762 0.32369006 0.13260351 0.71598133 0.50456804 0.99844555]


In [ ]:
import numpy as np

def evaluate_model(input_values):
    """Replace this with your actual model evaluation function."""
    # This is a placeholder - replace with your actual calculation.
    # Here, we'll simulate some calculation with input_values:
    output = sum(input_values) ** 2
    return output

def random_search(num_iterations, lower_bounds, upper_bounds):
    """Performs a random search for optimal parameters."""
    best_params = None
    best_output = float('inf')  # Initialize with a very large value

    for _ in range(num_iterations):
        # Generate random parameters within the specified bounds
        params = [np.random.uniform(lower_bounds[i], upper_bounds[i])
                  for i in range(len(lower_bounds))]

        # Evaluate the model with the random parameters
        output = evaluate_model(params)

        # Update best parameters if the current output is better
        if output < best_output:
            best_output = output
            best_params = params

    return best_params, best_output

# Define lower and upper bounds for each parameter
lower_bounds = [0.0, -1.0, 0.0, 0.0, 0.0, 0.2]  # Example bounds
upper_bounds = [1.0, 1.0, 1.0, 1.0, 1.0, 0.8]  # Example bounds

# Perform random search for 1000 iterations
num_iterations = 1000
best_params, best_output = random_search(num_iterations, lower_bounds, upper_bounds)

print("Best parameters:", best_params)
print("Best output:", best_output)

Best parameters: [0.04209292637180606, -0.952208289202376, 0.017854122267532357, 0.08615036403419751, 0.580354357277392, 0.282113520228861]
Best output: 0.003176111559168127


In [ ]:
import numpy as np

# New data point
new_input = np.array([0.022092, -0.752208, -0.001222, -0.026150, -0.380354, -0.182113])
new_output = np.float64(0.04984466971422817)

# Load existing data
initial_inputs = np.load('/content/initial_inputs.npy')
initial_outputs = np.load('/content/initial_outputs.npy')

# Add the new data point
updated_inputs = np.vstack([initial_inputs, new_input])
updated_outputs = np.append(initial_outputs, new_output)

# Save the updated data
np.save('/content/initial_inputs.npy', updated_inputs)
np.save('/content/initial_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# New data points
new_input1 = np.array([0.022092, -0.752208, -0.001222, -0.026150, -0.380354, -0.182113])
new_output1 = np.float64(0.04984466971422817)

new_input2 = np.array([0.042092, 0.952208, 0.011222, 0.08615 , 0.580354, 0.282113])
new_output2 = np.float64(0.02556460085136989)

# Load existing data
initial_inputs = np.load('/content/initial_inputs.npy')
initial_outputs = np.load('/content/initial_outputs.npy')

# Add the new data points
updated_inputs = np.vstack([initial_inputs, new_input1, new_input2])
updated_outputs = np.append(initial_outputs, [new_output1, new_output2])

# Save the updated data
np.save('/content/initial_inputs.npy', updated_inputs)
np.save('/content/initial_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)


Updated Inputs:
 [[ 0.27262382  0.32449536  0.89710881  0.83295115  0.15406269  0.79586362]
 [ 0.54300258  0.9246939   0.34156746  0.64648585  0.71844033  0.34313266]
 [ 0.09083225  0.66152938  0.06593091  0.25857701  0.96345285  0.6402654 ]
 [ 0.11886697  0.61505494  0.90581639  0.8553003   0.41363143  0.58523563]
 [ 0.63021764  0.8380969   0.68001305  0.73189509  0.52673671  0.34842921]
 [ 0.76491917  0.25588292  0.60908422  0.21807904  0.32294277  0.09579366]
 [ 0.05789554  0.49167222  0.24742222  0.21811844  0.42042833  0.73096984]
 [ 0.19525188  0.07922665  0.55458046  0.17056682  0.01494418  0.10703171]
 [ 0.64230298  0.83687455  0.02179269  0.10148801  0.68307083  0.6924164 ]
 [ 0.78994255  0.19554501  0.57562333  0.07365919  0.25904917  0.05109986]
 [ 0.52849733  0.45742436  0.36009569  0.36204551  0.81689098  0.63747637]
 [ 0.72261522  0.01181284  0.06364591  0.16517311  0.07924415  0.35995166]
 [ 0.07566492  0.33450212  0.13273274  0.60831236  0.91838592  0.82233079]
 [ 0.942

In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials

# 1. Load your data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# 2. Define your model and evaluation function
def evaluate_model(params):
    """Objective function to minimize.

    Args:
        params (list): List of hyperparameter values.

    Returns:
        dict: Dictionary with 'loss' (the metric to minimize)
              and 'status': STATUS_OK.
    """
    # --- YOUR MODEL TRAINING AND EVALUATION CODE HERE ---
    # 1. Create your model instance (e.g

In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval

# 1. Load your data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# 2. Define your model and evaluation function
def evaluate_model(params):
    """Objective function to minimize.

    Args:
        params (dict): Dictionary of hyperparameter values.

    Returns:
        dict: Dictionary with 'loss' (the metric to minimize)
              and 'status': STATUS_OK.
    """
    # --- YOUR MODEL TRAINING AND EVALUATION CODE HERE ---
    # 1. Create your model instance (e.g., using scikit-learn, TensorFlow, etc.)
    #    - Example: model = MyModel(**params)
    # 2. Train the model on your data (updated_inputs, updated_outputs)
    #    - Example: model.fit(updated_inputs, updated_outputs)
    # 3. Evaluate the model (e.g., using cross-validation or a validation set)
    #    - Example: loss = model.evaluate(validation_data)
    # ---------------------------------------------------

    # Example (replace with your actual metric):
    # loss = calculate_loss_function(model_predictions, updated_outputs)

    return {'loss': loss, 'status': STATUS_OK}  # Return the loss and status

# 3. Define the hyperparameter space
space = {
    'param1': hp.uniform('param1', 0.0, 1.0),  # Example: learning rate
    'param2': hp.choice('param2', [10, 20, 30]),  # Example: number of trees
    # ... add other hyperparameters and their ranges ...
    'param6': hp.uniform('param6', 0.2, 0.8),  # Example: regularization strength
}

# 4. Run the optimization
trials = Trials()
best = fmin(evaluate_model, space, algo=tpe.suggest, max_evals=100, trials=trials)

# 5. Get the best hyperparameters and next query point
best_params = space_eval(space, best)
next_query = [best_params[f'param{i}'] for i in range(1, 7)]  # Assuming 6 params

print("Best hyperparameters:", best_params)
print("Next query point:", next_query)

  0%|          | 0/100 [00:00<?, ?trial/s, best loss=?]

ERROR:hyperopt.fmin:job exception: name 'loss' is not defined


  0%|          | 0/100 [00:00<?, ?trial/s, best loss=?]


NameError: name 'loss' is not defined

In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval

# 1. Load your data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# 2. Define your model and evaluation function
def evaluate_model(params):
    """Objective function to minimize.

    Args:
        params (dict): Dictionary of hyperparameter values.

    Returns:
        dict: Dictionary with 'loss' (the metric to minimize)
              and 'status': STATUS_OK.
    """
    # --- YOUR MODEL TRAINING AND EVALUATION CODE HERE ---
    # 1. Create your model instance (e.g

In [ ]:
import numpy as np

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')  # You might need outputs later

# Get the bounds for each dimension from the existing data
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

# Generate a random query within the bounds
next_query = [np.random.uniform(lower_bounds[i], upper_bounds[i]) for i in range(updated_inputs.shape[1])]

print("Next query (within data bounds):", next_query)

Next query (within data bounds): [0.5647971899129237, 0.4821495822537434, 0.8269304933870958, 0.3886561482728098, 0.26902581888607763, 0.3225207124535907]


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np

# New data points
new_input = np.array([0.042092, 0.952208, 0.011222, 0.08615 , 0.580354, 0.282113])
new_output = np.float64(0.02556460085136989)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data points
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# New data points
new_input = np.array([0.022092, 0.752208, 0.001222, 0.02615 , 0.380354, 0.182113])
new_output = np.float64(0.04984466971422817)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data points
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# New data points
new_input = np.array([0.564797, 0.482149, 0.82693 , 0.388656, 0.269025, 0.32252 ])
new_output = np.float64(0.4818420763725011)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data points
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')  # You might need outputs later

# Get the bounds for each dimension from the existing data
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

# Generate a random query within the bounds
next_query = [np.random.uniform(lower_bounds[i], upper_bounds[i]) for i in range(updated_inputs.shape[1])]

print("Next query (within data bounds):", next_query)

Next query (within data bounds): [0.21368006036666395, 0.6667364130791827, 0.48094701454784344, 0.47571050773556006, 0.7805980856849987, 0.9262086430784259]


In [ ]:
import numpy as np

# New data point
new_input = np.array([0.21368 , 0.666736, 0.480947, 0.47571 , 0.780598, 0.926208])
new_output = np.float64(0.08776440810057257)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data point
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials

# Define the lower and upper bounds for param1
lower_bound1 = 0.0  # Replace with your desired lower bound
upper_bound1 = 1.0  # Replace with your desired upper bound

# Define the hyperparameter space
space = {
    'param1': hp.uniform('param1', lower_bound1, upper_bound1),
    # ... define other hyperparameters and their ranges ...
}

# Define the objective function
def objective(params):
    # ... your model training and evaluation code ...
    # Make sure 'loss' is calculated and defined within this function
    loss = 0  # Replace with your actual loss calculation
    return {'loss': loss, 'status': STATUS_OK}

# Run the optimization
trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, max_evals=100, trials=trials)

# Print the best hyperparameters
print("Best hyperparameters:", best)

100%|██████████| 100/100 [00:00<00:00, 443.44trial/s, best loss: 0.0]
Best hyperparameters: {'param1': np.float64(0.1712492353584124)}


In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# --- 1. Random Sampling within Data Bounds ---

# Get the bounds for each dimension
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

# Generate a random query within the bounds
random_query = [np.random.uniform(lower_bounds[i], upper_bounds[i]) for i in range(updated_inputs.shape[1])]

print("Next query (random):", random_query)


# --- 2. Hyperopt Optimization (TPE) ---

# Define your model and evaluation function (replace with your actual code)
def evaluate_model(params):
    """Objective function to minimize."""
    # Example: loss = calculate_loss_function(model_predictions, updated_outputs)
    loss = 0  # Replace with your actual loss calculation
    return {'loss': loss, 'status': STATUS_OK}

# Define the hyperparameter space (adjust ranges as needed)
space = {
    f'param{i}': hp.uniform(f'param{i}', lower_bounds[i-1], upper_bounds[i-1])
    for i in range(1, updated_inputs.shape[1] + 1)
}

# Run the optimization (adjust max_evals as needed)
trials = Trials()
best = fmin(evaluate_model, space, algo=tpe.suggest, max_evals=100, trials=trials)

# Get the best hyperparameters as the next query
tpe_query = [best[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)]

print("Next query (TPE):", tpe_query)

Next query (random): [0.6601273858375658, 0.7220699343391487, 0.6213089862085432, 0.7216320029740245, 0.7320775121837607, 0.2019921988652452]
100%|██████████| 100/100 [00:00<00:00, 103.61trial/s, best loss: 0.0]
Next query (TPE): [np.float64(0.7306135017797049), np.float64(0.42823850984689427), np.float64(0.8793033738502348), np.float64(0.2461812285462746), np.float64(0.7027738141758513), np.float64(0.13800714675467599)]


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np

# New data point
new_input = np.array([0.730613, 0.428238, 0.879303, 0.246181, 0.702773, 0.138007])
new_output = np.float64(0.03428418724022162)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data point
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)


Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# --- 1. Random Sampling within Data Bounds ---

# Get the bounds for each dimension
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

# Generate a random query within the bounds
random_query = [np.random.uniform(lower_bounds[i], upper_bounds[i]) for i in range(updated_inputs.shape[1])]

print("Next query (random):", random_query)


# --- 2. Hyperopt Optimization (TPE) ---

# Define your model and evaluation function (replace with your actual code)
def evaluate_model(params):
    """Objective function to minimize."""
    # Example: loss = calculate_loss_function(model_predictions, updated_outputs)
    loss = 0  # Replace with your actual loss calculation
    return {'loss': loss, 'status': STATUS_OK}

# Define the hyperparameter space (adjust ranges as needed)
space = {
    f'param{i}': hp.uniform(f'param{i}', lower_bounds[i-1], upper_bounds[i-1])
    for i in range(1, updated_inputs.shape[1] + 1)
}

# Run the optimization (adjust max_evals as needed)
trials = Trials()
best = fmin(evaluate_model, space, algo=tpe.suggest, max_evals=100, trials=trials)

# Get the best hyperparameters as the next query
tpe_query = [best[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)]

print("Next query (TPE):", tpe_query)

Next query (random): [0.8889439405356026, 0.670247478847027, 0.16374737187647556, 0.9426829558283024, 0.789906227290991, 0.8684240853575561]
100%|██████████| 100/100 [00:00<00:00, 112.14trial/s, best loss: 0.0]
Next query (TPE): [np.float64(0.7693619986918245), np.float64(0.3656174852625748), np.float64(0.9111688205795385), np.float64(0.1851196423689224), np.float64(0.7458073573534056), np.float64(0.07470110710699958)]


In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Define your model and evaluation function (replace with your actual code)
def evaluate_model(params):
    """Objective function to minimize."""
    # ... your code to create, train, and evaluate your model ...
    # Make sure 'loss' is calculated and defined within this function
    # This is just an example - replace with your actual logic
    # Assuming your model uses 'param1' and 'param2' from params
    model_output = params['param1'] * 2 + params['param2'] * 3
    loss = np.abs(model_output - updated_outputs.mean()) # Example loss calculation

    return {'loss': loss, 'status': STATUS_OK}

# Define the hyperparameter space (adjust ranges as needed)
space = {
    'param1': hp.uniform('param1', 0, 1),  # Example: range 0 to 1
    'param2': hp.uniform('param2', -1, 1), # Example: range -1 to 1
    # ... add other hyperparameters ...
}

# Run the optimization
trials = Trials()
best = fmin(evaluate_model, space, algo=tpe.suggest, max_evals=100, trials=trials)

# Get the next query
next_query = space_eval(space, best)
print("Next query:", next_query)

100%|██████████| 100/100 [00:00<00:00, 263.65trial/s, best loss: 0.03564421512334218]
Next query: {'param1': 0.5154556822386714, 'param2': -0.28630426726706953}


In [ ]:
import numpy as np

# New data point
new_input = np.array([0.769361, -0.365617, -0.911168, -0.185119, -0.745807, -0.074701])
new_output = np.float64(0.009609944961536127)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data point
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[ 0.27262382  0.32449536  0.89710881  0.83295115  0.15406269  0.79586362]
 [ 0.54300258  0.9246939   0.34156746  0.64648585  0.71844033  0.34313266]
 [ 0.09083225  0.66152938  0.06593091  0.25857701  0.96345285  0.6402654 ]
 [ 0.11886697  0.61505494  0.90581639  0.8553003   0.41363143  0.58523563]
 [ 0.63021764  0.8380969   0.68001305  0.73189509  0.52673671  0.34842921]
 [ 0.76491917  0.25588292  0.60908422  0.21807904  0.32294277  0.09579366]
 [ 0.05789554  0.49167222  0.24742222  0.21811844  0.42042833  0.73096984]
 [ 0.19525188  0.07922665  0.55458046  0.17056682  0.01494418  0.10703171]
 [ 0.64230298  0.83687455  0.02179269  0.10148801  0.68307083  0.6924164 ]
 [ 0.78994255  0.19554501  0.57562333  0.07365919  0.25904917  0.05109986]
 [ 0.52849733  0.45742436  0.36009569  0.36204551  0.81689098  0.63747637]
 [ 0.72261522  0.01181284  0.06364591  0.16517311  0.07924415  0.35995166]
 [ 0.07566492  0.33450212  0.13273274  0.60831236  0.91838592  0.82233079]
 [ 0.942

In [ ]:
import numpy as np

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Define the new input array
new_input_value = np.array([0.769361, 0.365617, 0.911168, 0.185119, 0.745807, 0.074701])

# Check if there are any inputs to modify
if updated_inputs.shape[0] > 0:
    # Change the last updated input
    updated_inputs[-1] = new_input_value
    print("Last input updated successfully.")
else:
    print("No inputs found to update.")

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data saved successfully.")

Last input updated successfully.
Data saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Find the index of the minimum output value
min_output_index = np.argmin(updated_outputs)

# Get the input values corresponding to the minimum output
corresponding_input = updated_inputs[min_output_index]

print("Index of minimum output:", min_output_index)
print("Corresponding input values:", corresponding_input)
print("Minimum output value:", updated_outputs[min_output_index])

# You can also find the indices of the top N lowest outputs
N = 5  # Change N to the number of top inputs you want to see
top_N_indices = np.argsort(updated_outputs)[:N]

print(f"\nTop {N} most promising inputs (lowest outputs):")
for i in top_N_indices:
    print(f"Index: {i}, Input: {updated_inputs[i]}, Output: {updated_outputs[i]}")

Index of minimum output: 19
Corresponding input values: [0.87987128 0.39796199 0.00363456 0.95699064 0.26451373 0.11486924]
Minimum output value: 0.0027014650245082332

Top 5 most promising inputs (lowest outputs):
Index: 19, Input: [0.87987128 0.39796199 0.00363456 0.95699064 0.26451373 0.11486924], Output: 0.0027014650245082332
Index: 27, Input: [0.84686697 0.14242917 0.06066859 0.75629213 0.5523983  0.08130609], Output: 0.003134333310934767
Index: 26, Input: [0.93246638 0.48881189 0.25860774 0.95624344 0.19042781 0.51985176], Output: 0.003777479616578685
Index: 21, Input: [0.22634792 0.11502581 0.82474966 0.94538372 0.90531153 0.95101392], Output: 0.007016027558514625
Index: 2, Input: [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ], Output: 0.007503236678049401


In [ ]:
import numpy as np

# New data point
new_input = np.array([0.888943, 0.670247, 0.163747, 0.942682, 0.789906, 0.868424])
new_output = np.float64(6.284475532014832e-05)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data point
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
import warnings
from scipy.special import erf  # Import erf from scipy.special

# Suppress ConvergenceWarning for GaussianProcessRegressor
warnings.filterwarnings("ignore", category=UserWarning)

# 1. Load your data
# Assuming you have updated_inputs.npy and updated_outputs.npy from previous steps
try:
    updated_inputs = np.load('/content/updated_inputs.npy')
    updated_outputs = np.load('/content/updated_outputs.npy')
except FileNotFoundError:
    print("Error: updated_inputs.npy or updated_outputs.npy not found.")
    # You might want to handle this case, perhaps by starting with initial data
    # For this example, we'll assume the files exist from previous steps.
    exit() # Exit if data not found for demonstration

# Ensure data has at least two points for Gaussian Process
if updated_inputs.shape[0] < 2:
    print("Need at least 2 data points to train the Gaussian Process.")
    # You would typically add some initial random points here if starting fresh
    # For this example, we'll assume you have sufficient data.
    exit()

# 2. Choose and Train a Surrogate Model (Gaussian Process Example)
# Define the kernel for the Gaussian Process
# You might need to tune the kernel parameters
kernel = C(1.0, (1e-3, 1e3)) * RBF(1.0, (1e-2, 1e2))
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10)

# Train the Gaussian Process on your data
gp.fit(updated_inputs, updated_outputs)

# 3. Define an Acquisition Function (Expected Improvement Example)

def expected_improvement(X, gp_model, xi=0.01):
    """
    Calculates the Expected Improvement for a given set of input points.

    Args:
        X (np.ndarray): Input points to evaluate the acquisition function.
        gp_model (GaussianProcessRegressor): Trained Gaussian Process model.
        xi (float): Exploration parameter (higher xi encourages more exploration).

    Returns:
        np.ndarray: Expected Improvement values for the input points.
    """
    mu, sigma = gp_model.predict(X, return_std=True)
    sigma = sigma.reshape(-1, 1)

    # Avoid division by zero
    with np.errstate(divide='warn'):
        imp = mu - np.min(gp_model.y_train_) - xi
        Z = imp / sigma
        # Use the imported erf function from scipy.special
        ei = imp * (0.5 * (1 + erf(Z / np.sqrt(2)))) + sigma * (0.5 * np.exp(-0.5 * Z**2) / np.sqrt(2 * np.pi))

    ei[sigma == 0.0] = 0.0 # Handle cases where uncertainty is zero
    return ei

# Define the objective function for Hyperopt (maximize Expected Improvement)
def hyperopt_objective(params):
    """
    Objective function for Hyperopt to maximize the acquisition function.

    Args:
        params (dict): Dictionary of hyperparameter values (the input point).

    Returns:
        dict: Dictionary with 'loss' (negative EI) and 'status'.
    """
    # Convert params dict to a numpy array
    X = np.array([[params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)]])

    # Calculate Expected Improvement (we want to maximize EI, so minimize -EI)
    ei = expected_improvement(X, gp)

    # Return the negative EI as the loss for Hyperopt
    return {'loss': -ei[0, 0], 'status': STATUS_OK}


# 4. Set up Hyperopt
# Define the search space for the input parameters (same as your original input space)
# Assuming your input space bounds are known or can be inferred from data
# For this example, we'll use the min/max of the existing data as bounds
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

space = {
    f'param{i}': hp.uniform(f'param{i}', lower_bounds[i-1], upper_bounds[i-1])
    for i in range(1, updated_inputs.shape[1] + 1)
}

# 5. Run Hyperopt
trials = Trials()
# We want to maximize the acquisition function, which is equivalent to minimizing the negative acquisition function.
# Hyperopt by default minimizes, so we use the negative EI as the loss.
best = fmin(fn=hyperopt_objective,
            space=space,
            algo=tpe.suggest,
            max_evals=100,  # You can adjust the number of evaluations for Hyperopt
            trials=trials)

# Get the best parameters found by Hyperopt (this is your next query point)
next_query_params = space_eval(space, best)
next_query = np.array([next_query_params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)])

print("Next query point suggested by Bayesian Optimization:", next_query)

# Now you would evaluate your actual "Function 7" with this 'next_query'
# After evaluating, you would add the new input/output pair to your data
# and repeat the process.

100%|██████████| 100/100 [00:01<00:00, 88.32trial/s, best loss: -0.9652256313780113]
Next query point suggested by Bayesian Optimization: [0.07446711 0.56622319 0.50002558 0.13773029 0.36539026 0.52923013]


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Find the indices of the top 5 lowest outputs
# np.argsort returns the indices that would sort an array
# We take the first 5 indices to get the indices of the smallest values
top_5_indices = np.argsort(updated_outputs)[:5]

print("Top 5 inputs corresponding to the 5 best (lowest) outputs:")
# Iterate through the top 5 indices and print the input and output for each
for i in top_5_indices:
    print(f"Input: {updated_inputs[i]}, Output: {updated_outputs[i]}")

Top 5 inputs corresponding to the 5 best (lowest) outputs:
Input: [0.888943 0.670247 0.163747 0.942682 0.789906 0.868424], Output: 6.284475532014832e-05
Input: [0.87987128 0.39796199 0.00363456 0.95699064 0.26451373 0.11486924], Output: 0.0027014650245082332
Input: [0.84686697 0.14242917 0.06066859 0.75629213 0.5523983  0.08130609], Output: 0.003134333310934767
Input: [0.93246638 0.48881189 0.25860774 0.95624344 0.19042781 0.51985176], Output: 0.003777479616578685
Input: [0.22634792 0.11502581 0.82474966 0.94538372 0.90531153 0.95101392], Output: 0.007016027558514625


In [ ]:
import numpy as np

# New data point
new_input = np.array([0.074467, 0.566223, 0.500025, 0.13773 , 0.36539 , 0.52923 ])
new_output = np.float64(1.2998634296892917)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data point
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
import warnings
from scipy.special import erf  # Import erf from scipy.special

# Suppress ConvergenceWarning for GaussianProcessRegressor
warnings.filterwarnings("ignore", category=UserWarning)

# 1. Load your data (or use the data you provided)
# Assuming you have updated_inputs.npy and updated_outputs.npy from previous steps
try:
    updated_inputs = np.load('/content/updated_inputs.npy')
    updated_outputs = np.load('/content/updated_outputs.npy')
except FileNotFoundError:
    print("Error: updated_inputs.npy or updated_outputs.npy not found. Using provided data.")
    # Use the data provided in the question if files are not found
    updated_inputs = np.array([
        [0.87987128, 0.39796199, 0.00363456, 0.95699064, 0.26451373, 0.11486924],
        [0.84686697, 0.14242917, 0.06066859, 0.75629213, 0.5523983 , 0.08130609],
        [0.93246638, 0.48881189, 0.25860774, 0.95624344, 0.19042781, 0.51985176],
        [0.22634792, 0.11502581, 0.82474966, 0.94538372, 0.90531153, 0.95101392]
    ])
    updated_outputs = np.array([
        0.0027014650245082332,
        0.003134333310934767,
        0.003777479616578685,
        0.007016027558514625
    ])


# Ensure data has at least two points for Gaussian Process
if updated_inputs.shape[0] < 2:
    print("Need at least 2 data points to train the Gaussian Process.")
    # You would typically add some initial random points here if starting fresh
    # For this example, we'll assume you have sufficient data.
    # If you just have the 4 points, the GP might not be very accurate,
    # but we can proceed for demonstration.
    pass


# 2. Choose and Train a Surrogate Model (Gaussian Process Example)
# Define the kernel for the Gaussian Process
# You might need to tune the kernel parameters
kernel = C(1.0, (1e-3, 1e3)) * RBF(1.0, (1e-2, 1e2))
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10)

# Train the Gaussian Process on your data
gp.fit(updated_inputs, updated_outputs)

# 3. Define an Acquisition Function (Expected Improvement Example)

def expected_improvement(X, gp_model, xi=0.01):
    """
    Calculates the Expected Improvement for a given set of input points.

    Args:
        X (np.ndarray): Input points to evaluate the acquisition function.
        gp_model (GaussianProcessRegressor): Trained Gaussian Process model.
        xi (float): Exploration parameter (higher xi encourages more exploration).

    Returns:
        np.ndarray: Expected Improvement values for the input points.
    """
    mu, sigma = gp_model.predict(X, return_std=True)
    sigma = sigma.reshape(-1, 1)

    # Avoid division by zero
    with np.errstate(divide='warn'):
        imp = mu - np.min(gp_model.y_train_) - xi
        Z = imp / sigma
        # Use the imported erf function from scipy.special
        ei = imp * (0.5 * (1 + erf(Z / np.sqrt(2)))) + sigma * (0.5 * np.exp(-0.5 * Z**2) / np.sqrt(2 * np.pi))

    ei[sigma == 0.0] = 0.0 # Handle cases where uncertainty is zero
    return ei

# Define the objective function for Hyperopt (maximize Expected Improvement)
def hyperopt_objective(params):
    """
    Objective function for Hyperopt to maximize the acquisition function.

    Args:
        params (dict): Dictionary of hyperparameter values (the input point).

    Returns:
        dict: Dictionary with 'loss' (negative EI) and 'status'.
    """
    # Convert params dict to a numpy array
    X = np.array([[params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)]])

    # Calculate Expected Improvement (we want to maximize EI, so minimize -EI)
    ei = expected_improvement(X, gp)

    # Return the negative EI as the loss for Hyperopt
    return {'loss': -ei[0, 0], 'status': STATUS_OK}


# 4. Set up Hyperopt
# Define the search space for the input parameters (same as your original input space)
# Assuming your input space bounds are known or can be inferred from data
# For this example, we'll use the min/max of the existing data as bounds
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

space = {
    f'param{i}': hp.uniform(f'param{i}', lower_bounds[i-1], upper_bounds[i-1])
    for i in range(1, updated_inputs.shape[1] + 1)
}

# 5. Run Hyperopt
trials = Trials()
# We want to maximize the acquisition function, which is equivalent to minimizing the negative acquisition function.
# Hyperopt by default minimizes, so we use the negative EI as the loss.
best = fmin(fn=hyperopt_objective,
            space=space,
            algo=tpe.suggest,
            max_evals=100,  # You can adjust the number of evaluations for Hyperopt
            trials=trials)

# Get the best parameters found by Hyperopt (this is your next query point)
next_query_params = space_eval(space, best)
next_query = np.array([next_query_params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)])

print("Next query point suggested by Bayesian Optimization:", next_query)

100%|██████████| 100/100 [00:01<00:00, 89.44trial/s, best loss: -1.3554932573798846]
Next query point suggested by Bayesian Optimization: [0.037152   0.52563243 0.46751738 0.07960108 0.42121706 0.75945791]


In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
import warnings
from scipy.special import erf  # Import erf from scipy.special

# Suppress ConvergenceWarning for GaussianProcessRegressor
warnings.filterwarnings("ignore", category=UserWarning)

# 1. Load your data (or use the data you provided)
# Assuming you have updated_inputs.npy and updated_outputs.npy from previous steps
try:
    updated_inputs = np.load('/content/updated_inputs.npy')
    updated_outputs = np.load('/content/updated_outputs.npy')
except FileNotFoundError:
    print("Error: updated_inputs.npy or updated_outputs.npy not found.")
    # Handle the case where files are not found, maybe exit or use dummy data
    # For demonstration, we'll exit if data is not found.
    # In a real application, you might want to load initial data or handle this differently.
    exit()


# Ensure data has at least two points for Gaussian Process
if updated_inputs.shape[0] < 2:
    print("Need at least 2 data points to train the Gaussian Process.")
    # You would typically add some initial random points here if starting fresh
    # For this example, we'll assume you have sufficient data loaded or exited.
    # If you just have the 4 points, the GP might not be very accurate,
    # but we can proceed for demonstration if you commented out the exit().
    pass


# 2. Choose and Train a Surrogate Model (Gaussian Process Example)
# Define the kernel for the Gaussian Process
# You might need to tune the kernel parameters
kernel = C(1.0, (1e-3, 1e3)) * RBF(1.0, (1e-2, 1e2))
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10)

# Train the Gaussian Process on your data
gp.fit(updated_inputs, updated_outputs)

# 3. Define an Acquisition Function (Expected Improvement Example)

def expected_improvement(X, gp_model, xi=0.01):
    """
    Calculates the Expected Improvement for a given set of input points.

    Args:
        X (np.ndarray): Input points to evaluate the acquisition function.
        gp_model (GaussianProcessRegressor): Trained Gaussian Process model.
        xi (float): Exploration parameter (higher xi encourages more exploration).

    Returns:
        np.ndarray: Expected Improvement values for the input points.
    """
    mu, sigma = gp_model.predict(X, return_std=True)
    sigma = sigma.reshape(-1, 1)

    # Avoid division by zero
    with np.errstate(divide='warn'):
        imp = mu - np.min(gp_model.y_train_) - xi
        Z = imp / sigma
        # Use the imported erf function from scipy.special
        ei = imp * (0.5 * (1 + erf(Z / np.sqrt(2)))) + sigma * (0.5 * np.exp(-0.5 * Z**2) / np.sqrt(2 * np.pi))

    ei[sigma == 0.0] = 0.0 # Handle cases where uncertainty is zero
    return ei

# Define the objective function for Hyperopt (maximize Expected Improvement)
def hyperopt_objective(params):
    """
    Objective function for Hyperopt to maximize the acquisition function.

    Args:
        params (dict): Dictionary of hyperparameter values (the input point).

    Returns:
        dict: Dictionary with 'loss' (negative EI) and 'status'.
    """
    # Convert params dict to a numpy array
    X = np.array([[params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)]])

    # Calculate Expected Improvement (we want to maximize EI, so minimize -EI)
    ei = expected_improvement(X, gp)

    # Return the negative EI as the loss for Hyperopt
    return {'loss': -ei[0, 0], 'status': STATUS_OK}


# 4. Set up Hyperopt
# Define the search space for the input parameters (same as your original input space)
# Assuming your input space bounds are known or can be inferred from data
# For this example, we'll use the min/max of the existing data as bounds
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

space = {
    f'param{i}': hp.uniform(f'param{i}', lower_bounds[i-1], upper_bounds[i-1])
    for i in range(1, updated_inputs.shape[1] + 1)
}

# 5. Run Hyperopt
trials = Trials()
# We want to maximize the acquisition function, which is equivalent to minimizing the negative acquisition function.
# Hyperopt by default minimizes, so we use the negative EI as the loss.
best = fmin(fn=hyperopt_objective,
            space=space,
            algo=tpe.suggest,
            max_evals=100,  # You can adjust the number of evaluations for Hyperopt
            trials=trials)

# Get the best parameters found by Hyperopt (this is your next query point)
next_query_params = space_eval(space, best)
next_query = np.array([next_query_params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)])

print("Next query point suggested by Bayesian Optimization:", next_query)

100%|██████████| 100/100 [00:01<00:00, 81.91trial/s, best loss: -1.1592915171542941]
Next query point suggested by Bayesian Optimization: [0.16122553 0.2851096  0.31579903 0.35059764 0.38083297 0.7036587 ]


In [ ]:
import numpy as np

# New data point
new_input = np.array([0.161225, 0.285109, 0.315799, 0.350597, 0.380832, 0.703658])
new_output = np.float64(2.5222412084963666)

# Load existing data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Add the new data point
updated_inputs = np.vstack([updated_inputs, new_input])
updated_outputs = np.append(updated_outputs, new_output)

# Save the updated data
np.save('/content/updated_inputs.npy', updated_inputs)
np.save('/content/updated_outputs.npy', updated_outputs)

print("Data appended and saved successfully.")

Data appended and saved successfully.


In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Print the contents
print("Updated Inputs:\n", updated_inputs)
print("\nUpdated Outputs:\n", updated_outputs)

Updated Inputs:
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03

In [ ]:
import numpy as np

# Load the updated data
updated_inputs = np.load('/content/updated_inputs.npy')
updated_outputs = np.load('/content/updated_outputs.npy')

# Find the indices of the top 5 lowest outputs
# np.argsort returns the indices that would sort an array
# We take the first 5 indices to get the indices of the smallest values
top_5_indices = np.argsort(updated_outputs)[:5]

print("Top 5 inputs corresponding to the 5 best (lowest) outputs:")
# Iterate through the top 5 indices and print the input and output for each
for i in top_5_indices:
    print(f"Input: {updated_inputs[i]}, Output: {updated_outputs[i]}")

Top 5 inputs corresponding to the 5 best (lowest) outputs:
Input: [0.888943 0.670247 0.163747 0.942682 0.789906 0.868424], Output: 6.284475532014832e-05
Input: [0.87987128 0.39796199 0.00363456 0.95699064 0.26451373 0.11486924], Output: 0.0027014650245082332
Input: [0.84686697 0.14242917 0.06066859 0.75629213 0.5523983  0.08130609], Output: 0.003134333310934767
Input: [0.93246638 0.48881189 0.25860774 0.95624344 0.19042781 0.51985176], Output: 0.003777479616578685
Input: [0.22634792 0.11502581 0.82474966 0.94538372 0.90531153 0.95101392], Output: 0.007016027558514625


In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
import warnings
from scipy.special import erf  # Import erf from scipy.special

# Suppress ConvergenceWarning for GaussianProcessRegressor
warnings.filterwarnings("ignore", category=UserWarning)

# 1. Load your data (or use the data you provided)
# Assuming you have updated_inputs.npy and updated_outputs.npy from previous steps
try:
    updated_inputs = np.load('/content/updated_inputs.npy')
    updated_outputs = np.load('/content/updated_outputs.npy')
except FileNotFoundError:
    print("Error: updated_inputs.npy or updated_outputs.npy not found. Using provided data.")
    # Use the data provided in the question if files are not found
    updated_inputs = np.array([
        [0.87987128, 0.39796199, 0.00363456, 0.95699064, 0.26451373, 0.11486924],
        [0.84686697, 0.14242917, 0.06066859, 0.75629213, 0.5523983 , 0.08130609],
        [0.93246638, 0.48881189, 0.25860774, 0.95624344, 0.19042781, 0.51985176],
        [0.22634792, 0.11502581, 0.82474966, 0.94538372, 0.90531153, 0.95101392]
    ])
    updated_outputs = np.array([
        0.0027014650245082332,
        0.003134333310934767,
        0.003777479616578685,
        0.007016027558514625
    ])


# Ensure data has at least two points for Gaussian Process
if updated_inputs.shape[0] < 2:
    print("Need at least 2 data points to train the Gaussian Process.")
    # You would typically add some initial random points here if starting fresh
    # For this example, we'll assume you have sufficient data.
    # If you just have the 4 points, the GP might not be very accurate,
    # but we can proceed for demonstration.
    pass


# 2. Choose and Train a Surrogate Model (Gaussian Process Example)
# Define the kernel for the Gaussian Process
# You might need to tune the kernel parameters
kernel = C(1.0, (1e-3, 1e3)) * RBF(1.0, (1e-2, 1e2))
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10)

# Train the Gaussian Process on your data
gp.fit(updated_inputs, updated_outputs)

# 3. Define an Acquisition Function (Expected Improvement Example)

def expected_improvement(X, gp_model, xi=0.01):
    """
    Calculates the Expected Improvement for a given set of input points.

    Args:
        X (np.ndarray): Input points to evaluate the acquisition function.
        gp_model (GaussianProcessRegressor): Trained Gaussian Process model.
        xi (float): Exploration parameter (higher xi encourages more exploration).

    Returns:
        np.ndarray: Expected Improvement values for the input points.
    """
    mu, sigma = gp_model.predict(X, return_std=True)
    sigma = sigma.reshape(-1, 1)

    # Avoid division by zero
    with np.errstate(divide='warn'):
        imp = mu - np.min(gp_model.y_train_) - xi
        Z = imp / sigma
        # Use the imported erf function from scipy.special
        ei = imp * (0.5 * (1 + erf(Z / np.sqrt(2)))) + sigma * (0.5 * np.exp(-0.5 * Z**2) / np.sqrt(2 * np.pi))

    ei[sigma == 0.0] = 0.0 # Handle cases where uncertainty is zero
    return ei

# Define the objective function for Hyperopt (maximize Expected Improvement)
def hyperopt_objective(params):
    """
    Objective function for Hyperopt to maximize the acquisition function.

    Args:
        params (dict): Dictionary of hyperparameter values (the input point).

    Returns:
        dict: Dictionary with 'loss' (negative EI) and 'status'.
    """
    # Convert params dict to a numpy array
    X = np.array([[params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)]])

    # Calculate Expected Improvement (we want to maximize EI, so minimize -EI)
    ei = expected_improvement(X, gp)

    # Return the negative EI as the loss for Hyperopt
    return {'loss': -ei[0, 0], 'status': STATUS_OK}


# 4. Set up Hyperopt
# Define the search space for the input parameters (same as your original input space)
# Assuming your input space bounds are known or can be inferred from data
# For this example, we'll use the min/max of the existing data as bounds
lower_bounds = updated_inputs.min(axis=0)
upper_bounds = updated_inputs.max(axis=0)

space = {
    f'param{i}': hp.uniform(f'param{i}', lower_bounds[i-1], upper_bounds[i-1])
    for i in range(1, updated_inputs.shape[1] + 1)
}

# 5. Run Hyperopt
trials = Trials()
# We want to maximize the acquisition function, which is equivalent to minimizing the negative acquisition function.
# Hyperopt by default minimizes, so we use the negative EI as the loss.
best = fmin(fn=hyperopt_objective,
            space=space,
            algo=tpe.suggest,
            max_evals=100,  # You can adjust the number of evaluations for Hyperopt
            trials=trials)

# Get the best parameters found by Hyperopt (this is your next query point)
next_query_params = space_eval(space, best)
next_query = np.array([next_query_params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)])

print("Next query point suggested by Bayesian Optimization:", next_query)

100%|██████████| 100/100 [00:00<00:00, 103.82trial/s, best loss: -2.0871600562085755]
Next query point suggested by Bayesian Optimization: [0.10017489 0.15543515 0.29305153 0.44281335 0.32304729 0.55353509]


In [ ]:
import numpy as np
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
import warnings
from scipy.special import erf

warnings.filterwarnings("ignore", category=UserWarning)

# Load your data
try:
    updated_inputs = np.load('/content/updated_inputs.npy')
    updated_outputs = np.load('/content/updated_outputs.npy')
except FileNotFoundError:
    print("Error: updated_inputs.npy or updated_outputs.npy not found.")
    exit()

if updated_inputs.shape[0] < 2:
    print("Need at least 2 data points to train the Gaussian Process.")
    exit()

# Find the best input (the one with the minimum output)
best_index = np.argmin(updated_outputs)
best_input = updated_inputs[best_index]

# Define a smaller search space around the best input for exploitation
# You'll need to define a suitable range for each parameter
# based on how much you want to explore around the best point.
# This is a crucial tuning step and might require experimentation.
exploitation_range = 0.1  # Example: define a range of 0.1 around each parameter of the best input

exploitation_space = {
    f'param{i}': hp.uniform(f'param{i}',
                            max(0, best_input[i-1] - exploitation_range),
                            min(1, best_input[i-1] + exploitation_range)) # Assuming parameters are in [0, 1]
    for i in range(1, updated_inputs.shape[1] + 1)
}

# Train the Gaussian Process
kernel = C(1.0, (1e-3, 1e3)) * RBF(1.0, (1e-2, 1e2))
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10)
gp.fit(updated_inputs, updated_outputs)

# Define the Expected Improvement function (same as before)
def expected_improvement(X, gp_model, xi=0.01):
    mu, sigma = gp_model.predict(X, return_std=True)
    sigma = sigma.reshape(-1, 1)
    with np.errstate(divide='warn'):
        imp = mu - np.min(gp_model.y_train_) - xi
        Z = imp / sigma
        ei = imp * (0.5 * (1 + erf(Z / np.sqrt(2)))) + sigma * (0.5 * np.exp(-0.5 * Z**2) / np.sqrt(2 * np.pi))
    ei[sigma == 0.0] = 0.0
    return ei

# Define the objective function for Hyperopt (maximize Expected Improvement)
def hyperopt_objective(params):
    X = np.array([[params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)]])
    ei = expected_improvement(X, gp)
    return {'loss': -ei[0, 0], 'status': STATUS_OK}

# Run Hyperopt with the exploitation space
trials_exploitation = Trials()
best_exploitation = fmin(fn=hyperopt_objective,
                         space=exploitation_space,
                         algo=tpe.suggest,
                         max_evals=50, # Use fewer evaluations for exploitation
                         trials=trials_exploitation)

# Get the next query from the exploitation search
next_query_exploitation_params = space_eval(exploitation_space, best_exploitation)
next_query_exploitation = np.array([next_query_exploitation_params[f'param{i}'] for i in range(1, updated_inputs.shape[1] + 1)])

print("Next query point suggested by Exploitation search:", next_query_exploitation)

100%|██████████| 50/50 [00:00<00:00, 141.62trial/s, best loss: -0.05868673104009349]
Next query point suggested by Exploitation search: [0.98436755 0.75794552 0.19501472 0.93237579 0.83413979 0.77675256]
